/* Ejercicio1: Volumen, Area de un Cilindro */
using System;
class Ejercicio1
{
    static void Main()
    {
        Console.WriteLine("Ingrese el radio del cilindro: ");
        float radio = float.Parse(Console.ReadLine());
        Console.WriteLine("Ingrese la altura del cilindro:");
        float altura = float.Parse(Console.ReadLine());
        /*
        Aplicando la formula del volumen del cilindro. 
        */

    }
}

